const mongoose=require('mongoose')
const userschema=new mongoose.Schema({
    name:{
        type:String,
        required:true
    },
    username:{
        type:String,
        required:true
    },
    email:{
        type:String,
        required:true
    },
    password:{
        type:String,
        required:true
    },
    photo:{
        type:String
    },
    about:{
        type:String
    },
    phone:{
        type:String
    },
    address:{
        type:String
    },
    education:[{
       institute:{
        type:String
       },
       degree:{
        type:String
       },
       start:{
        type:String
       },
       end:{
        type:String
       }
    }],
    profession:[{
        companyName:{
         type:String
        },
        jobType:{
            type:String
        },
        role:{
            type:String
        },
        startDate:{
            type:String
        },
        endDate:{
            type:String
        },
        isOngoing:{
           type:Boolean
        }

    }],
    social_link:{
        facebook:{
            type:String,
            default:""
        },
        instagram:{
            type:String,
            default:""
        },
        twitter:{
            type:String,
            default:""
        },
        linkedin:{
            type:String,
            default:""
        }
       }
    
})

mongoose.model("USER",userschema);